language: python

cache: pip

sudo: required

dist: trusty

python:
  - "2.7"
  - "3.6"

before_install:
  - pip install -U pip
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev gdal-bin libgdal-dev
  # postgis source compile dependencies:
  - sudo apt-get --yes install libjson-c-dev postgresql-server-dev-9.6
  # install postgis from source:
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
  # activate liblwgeom
  - sudo ldconfig 
  # Install numpy (required for rasterio)
  - pip install numpy
install:
  - pip install -e .

script:
  - python setup.py test

warnings_are_errors: true

notifications:
  email: false
