'''
Created on Nov 10, 2017

@author: agutierrez
'''

FILL = 1
CLEAR = 2
WATER = 4
CLOUD_SHADOW = 8
SNOW_ICE = 16
CLOUD = 32
CONFIDENCE_CLOUD = 192
CONFIDENCE_CIRRUS = 768
TERRAIN_OCCLUSION = 1024

FILL_SHIFT = 0
CLEAR_SHIFT = 1
WATER_SHIFT = 2
CLOUD_SHADOW_SHIFT = 3
SNOW_ICE_SHIFT = 4
CLOUD_SHIFT = 5
CONFIDENCE_CLOUD_SHIFT = 6
CONFIDENCE_CIRRUS_SHIFT = 8
TERRAIN_OCCLUSION_SHIFT = 10