# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landsatcatalog',
            name='acquisition_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='landsatcatalog',
            name='browse_url',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='landsatcatalog',
            name='cloud_full',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='landsatcatalog',
            name='day_night',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='landsatcatalog',
            name='ground_control_points_model',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='landsatcatalog',
            name='image_quality',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='landsatcatalog',
            name='landsat_product_id',
            field=models.CharField(default=-1, max_length=50),
        ),
        migrations.AddField(
            model_name='landsatcatalog',
            name='path',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='landsatcatalog',
            name='row',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='landsatcatalog',
            name='sensor',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
