# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0003_auto_20171027_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='LansatAWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('entity_id', models.CharField(max_length=100, unique=True)),
                ('acquisitionDate', models.DateTimeField(default=None)),
                ('cloudCover', models.FloatField(default=-1.0)),
                ('processingLevel', models.CharField(max_length=10, unique=True)),
                ('path', models.IntegerField(default=-1)),
                ('row', models.IntegerField(default=-1)),
                ('min_lat', models.FloatField(default=-1)),
                ('min_lon', models.FloatField(default=-1)),
                ('max_lat', models.FloatField(default=-1)),
                ('max_lon', models.FloatField(default=-1)),
                ('download_url', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
