# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0004_lansataws'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lansataws',
            name='download_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lansataws',
            name='entity_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lansataws',
            name='processingLevel',
            field=models.CharField(max_length=10),
        ),
    ]
