# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 21:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0007_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
