# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 04:05
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0009_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footprint_id', models.CharField(max_length=50)),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='mpoly',
            new_name='the_geom',
        ),
    ]
