# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0010_auto_20171205_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footprints',
            old_name='footprint_id',
            new_name='name',
        ),
    ]
