# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 04:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0012_auto_20171205_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
